server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: Anuj@888
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
